name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # 1. Create a temporary branch from the current state
          git checkout -b temp-hf-deploy
          
          # 2. Extract only the 'backend' folder to become the new root
          git filter-branch -f --prune-empty --subdirectory-filter backend temp-hf-deploy
          
          # 3. Force push this 'backend-only' history to HuggingFace
          git push --force https://rafidzenn:$HF_TOKEN@huggingface.co/spaces/rafidzenn/vault-bd-api temp-hf-deploy:main
